[platformio]
default_envs = twatchs3

; dùng factory example
; src_dir = ${platformio.libdeps_dir}/${platformio.default_envs}/LilyGoLib/examples/factory

boards_dir = ./boards


; ================= BASE =================
[env_arduino]
framework = arduino
platform = espressif32@6.5.0

upload_speed = 921600
monitor_speed = 115200

board_build.filesystem = fatfs
board_build.partitions = ${platformio.libdeps_dir}/${platformio.default_envs}/LilyGoLib/examples/factory/partitions.csv

build_flags =
    -D CORE_DEBUG_LEVEL=0

    ; ===== BẮT BUỘC chọn radio =====
    -D ARDUINO_LILYGO_LORA_SX1262

    ; ===== giảm lỗi RadioLib =====
    -D RADIOLIB_EXCLUDE_RF69
    -D RADIOLIB_EXCLUDE_SX1231
    -D RADIOLIB_EXCLUDE_CC1101
    -D RADIOLIB_EXCLUDE_SI443X
    -D RADIOLIB_EXCLUDE_SX128X
    -D RADIOLIB_EXCLUDE_NRF24
    -D RADIOLIB_EXCLUDE_RFM2X
    -D RADIOLIB_EXCLUDE_SX127X
    -D RADIOLIB_EXCLUDE_STM32WLX
    -D RADIOLIB_EXCLUDE_AFSK
    -D RADIOLIB_EXCLUDE_AX25
    -D RADIOLIB_EXCLUDE_HELLSCHREIBER
    -D RADIOLIB_EXCLUDE_MORSE
    -D RADIOLIB_EXCLUDE_RTTY
    -D RADIOLIB_EXCLUDE_SSTV
    -D RADIOLIB_EXCLUDE_DIRECT_RECEIVE
    -D RADIOLIB_EXCLUDE_APRS
    -D RADIOLIB_EXCLUDE_BELL

    -Wnarrowing

monitor_filters =
    default
    esp32_exception_decoder


; ===== LIB =====
lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGoLib
    lvgl/lvgl @ 9.4.0
    jgromes/RadioLib @ 7.4.0
    lewisxhe/XPowersLib @ 0.3.1
    lewisxhe/SensorLib @ 0.3.3
    mikalhart/TinyGPSPlus @ 1.0.3
    https://github.com/lewisxhe/ESP32-BLE-Keyboard-fork.git
    https://github.com/lewisxhe/ESP32-BLE-Mouse-fork.git
    earlephilhower/ESP8266Audio @ 2.0.0
    ESP32 BLE Arduino
    h2zero/NimBLE-Arduino @ 2.2.3


; ================= WATCH S3 =================
[env:twatchs3]
extends = env_arduino
board = lilygo-t-watch-s3

upload_speed = 921600

build_flags =
    ${env_arduino.build_flags}
    -D ARDUINO_T_WATCH_S3
    -I variants/lilygo_twatch_s3

lib_deps =
    ${env_arduino.lib_deps}
    https://github.com/tonhuisman/IRremoteESP8266/archive/refs/heads/feature/C++20-compatibility.zip